<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-R51096T" name="org.mavenpro.Retryanalyzer_testng" tests="6" failures="0" timestamp="2023-04-21T14:50:00 IST" time="0.010" errors="1">
  <testcase name="divbyzero1" time="0.001" classname="org.mavenpro.Retryanalyzer_testng">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.mavenpro.Retryanalyzer_testng.divbyzero1(Retryanalyzer_testng.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
  <testcase name="divbyzero1" time="0.006" classname="org.mavenpro.Retryanalyzer_testng">
    <skipped/>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
  <testcase name="divbyzero1" time="0.001" classname="org.mavenpro.Retryanalyzer_testng">
    <skipped/>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
  <testcase name="divbyzero1" time="0.000" classname="org.mavenpro.Retryanalyzer_testng">
    <skipped/>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
  <testcase name="divbyzero1" time="0.001" classname="org.mavenpro.Retryanalyzer_testng">
    <skipped/>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
  <testcase name="divbyzero1" time="0.001" classname="org.mavenpro.Retryanalyzer_testng">
    <skipped/>
  </testcase> <!-- divbyzero1 -->
  <system-out/>
</testsuite> <!-- org.mavenpro.Retryanalyzer_testng -->
